# LocalhostBridgeCore Bukkit-Side 配置文件
# 注意: 本插件未设置Token等安全验证，即对所有本地来源的操作是完全信任的，请确保所有使用端口无本地转发
# 警告: 127.0.0.1 上的所有服务端对本通信网络有完全的控制权，如果你不信任它们，请不要使用本插件
# 项目地址 https://github.com/MessyCraft/LocalhostBridgeCore
# (作者很讨厌繁琐的配置，尽量简约啦..)

# 访问端口，与BC端保持一致
access-port: 31013

# 唯一标识符，用于通讯时标记地址，更改后方可使用
unique: default

# 连接超时毫秒数，一般情况下你不需要更改此项
timeout: 50

# 读取超时毫秒数，防止连接堆积(实际最大响应时间仍由BC端控制)，一般情况下你不需要更改此项
read-timeout: 10000

# 调试模式，会输出一些详细信息。当调试启用时自动启用警告显示。
debug: false

# 是否显示警告，不建议关闭，除非造成刷屏
# 但即使如此，警告频繁下你应该寻找问题的根源而不是熟视无睹
show-warnings: true
